/* Copyright (c) 2012 Nordic Semiconductor. All Rights Reserved.
*
* The information contained herein is property of Nordic Semiconductor ASA.
* Terms and conditions of usage are described in detail in NORDIC
* SEMICONDUCTOR STANDARD SOFTWARE LICENSE AGREEMENT.
*
* Licensees are granted free, non-transferable use of the information. NO
* WARRANTY of ANY KIND is provided. This heading must NOT be removed from
* the file.
*/

/**
* This file is autogenerated by nRFgo Studio 1.15.1.2691
*/

#include "services.h"
#include "lib_aci.h"

static bool is_gap_device_name_set_requested = false;
static bool is_firmata_firmata_command_send_requested = false;
static bool is_firmata_firmata_command_ack_send_requested = false;
static bool is_firmata_firmata_command_set_requested = false;
static bool is_ble_bridge_device_id_send_requested = false;
static bool is_ble_bridge_device_id_ack_send_requested = false;
static bool is_ble_bridge_device_id_set_requested = false;
static bool is_ble_bridge_bridge_tx_send_requested = false;
static bool is_ble_bridge_bridge_tx_ack_send_requested = false;
static bool is_bleduino_manufacturer_name_string_set_requested = false;

static void *gap_device_name_set;
static uint8_t gap_device_name_set_size;
static void *firmata_firmata_command_tx;
static uint8_t firmata_firmata_command_tx_size;
static void *firmata_firmata_command_tx_ack;
static uint8_t firmata_firmata_command_tx_ack_size;
static void *firmata_firmata_command_set;
static uint8_t firmata_firmata_command_set_size;
static uint8_t ble_bridge_device_id_tx;
static uint8_t ble_bridge_device_id_tx_ack;
static uint8_t ble_bridge_device_id_set;
static void *ble_bridge_bridge_tx_tx;
static uint8_t ble_bridge_bridge_tx_tx_size;
static void *ble_bridge_bridge_tx_tx_ack;
static uint8_t ble_bridge_bridge_tx_tx_ack_size;
static void *bleduino_manufacturer_name_string_set;
static uint8_t bleduino_manufacturer_name_string_set_size;

static bool gap_device_name_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_GAP_DEVICE_NAME_SET, (void*)gap_device_name_set, gap_device_name_set_size));
}

void services_set_gap_device_name(void *src, int size)
{
  gap_device_name_set_size = size;
  gap_device_name_set = src;
  is_gap_device_name_set_requested = true;
  services_update_pipes();
}
static bool firmata_firmata_command_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_FIRMATA_FIRMATA_COMMAND_TX))
  {
    return(lib_aci_send_data(PIPE_FIRMATA_FIRMATA_COMMAND_TX, (void*)firmata_firmata_command_tx, firmata_firmata_command_tx_size));
  }
  return(false);
}

bool services_send_firmata_firmata_command(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_firmata_firmata_command_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_firmata_firmata_command_send_requested)
    {
      firmata_firmata_command_tx_size = size;
      firmata_firmata_command_tx = src;
      is_firmata_firmata_command_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    firmata_firmata_command_tx_size = size;
    firmata_firmata_command_tx = src;
    is_firmata_firmata_command_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool firmata_firmata_command_update_send_ack(void)
{
  if (lib_aci_is_pipe_available(PIPE_FIRMATA_FIRMATA_COMMAND_TX_ACK))
  {
    return(lib_aci_send_data(PIPE_FIRMATA_FIRMATA_COMMAND_TX_ACK, (void*)firmata_firmata_command_tx_ack, firmata_firmata_command_tx_ack_size));
  }
  return(false);
}

bool services_send_firmata_firmata_command_ack(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_firmata_firmata_command_ack_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_firmata_firmata_command_ack_send_requested)
    {
      firmata_firmata_command_tx_ack_size = size;
      firmata_firmata_command_tx_ack = src;
      is_firmata_firmata_command_ack_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    firmata_firmata_command_tx_ack_size = size;
    firmata_firmata_command_tx_ack = src;
    is_firmata_firmata_command_ack_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool firmata_firmata_command_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_FIRMATA_FIRMATA_COMMAND_SET, (void*)firmata_firmata_command_set, firmata_firmata_command_set_size));
}

void services_set_firmata_firmata_command(void *src, int size)
{
  firmata_firmata_command_set_size = size;
  firmata_firmata_command_set = src;
  is_firmata_firmata_command_set_requested = true;
  services_update_pipes();
}
static bool ble_bridge_device_id_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_BLE_BRIDGE_DEVICE_ID_TX))
  {
    return(lib_aci_send_data(PIPE_BLE_BRIDGE_DEVICE_ID_TX, (void*)&ble_bridge_device_id_tx, 1));
  }
  return(false);
}

bool services_send_ble_bridge_device_id(uint8_t src, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ble_bridge_device_id_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ble_bridge_device_id_send_requested)
    {
      ble_bridge_device_id_tx = src;
      is_ble_bridge_device_id_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ble_bridge_device_id_tx = src;
    is_ble_bridge_device_id_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ble_bridge_device_id_update_send_ack(void)
{
  if (lib_aci_is_pipe_available(PIPE_BLE_BRIDGE_DEVICE_ID_TX_ACK))
  {
    return(lib_aci_send_data(PIPE_BLE_BRIDGE_DEVICE_ID_TX_ACK, (void*)&ble_bridge_device_id_tx_ack, 1));
  }
  return(false);
}

bool services_send_ble_bridge_device_id_ack(uint8_t src, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ble_bridge_device_id_ack_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ble_bridge_device_id_ack_send_requested)
    {
      ble_bridge_device_id_tx_ack = src;
      is_ble_bridge_device_id_ack_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ble_bridge_device_id_tx_ack = src;
    is_ble_bridge_device_id_ack_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ble_bridge_device_id_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_BLE_BRIDGE_DEVICE_ID_SET, (void*)&ble_bridge_device_id_set, 1));
}

void services_set_ble_bridge_device_id(uint8_t src)
{
  ble_bridge_device_id_set = src;
  is_ble_bridge_device_id_set_requested = true;
  services_update_pipes();
}
static bool ble_bridge_bridge_tx_update_send(void)
{
  if (lib_aci_is_pipe_available(PIPE_BLE_BRIDGE_BRIDGE_TX_TX))
  {
    return(lib_aci_send_data(PIPE_BLE_BRIDGE_BRIDGE_TX_TX, (void*)ble_bridge_bridge_tx_tx, ble_bridge_bridge_tx_tx_size));
  }
  return(false);
}

bool services_send_ble_bridge_bridge_tx(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ble_bridge_bridge_tx_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ble_bridge_bridge_tx_send_requested)
    {
      ble_bridge_bridge_tx_tx_size = size;
      ble_bridge_bridge_tx_tx = src;
      is_ble_bridge_bridge_tx_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ble_bridge_bridge_tx_tx_size = size;
    ble_bridge_bridge_tx_tx = src;
    is_ble_bridge_bridge_tx_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool ble_bridge_bridge_tx_update_send_ack(void)
{
  if (lib_aci_is_pipe_available(PIPE_BLE_BRIDGE_BRIDGE_TX_TX_ACK))
  {
    return(lib_aci_send_data(PIPE_BLE_BRIDGE_BRIDGE_TX_TX_ACK, (void*)ble_bridge_bridge_tx_tx_ack, ble_bridge_bridge_tx_tx_ack_size));
  }
  return(false);
}

bool services_send_ble_bridge_bridge_tx_ack(void *src, int size, bool is_freshest_sample)
{
  if (false == is_freshest_sample)
  {
    if (true == is_ble_bridge_bridge_tx_ack_send_requested)
    {
      services_update_pipes();
    }
    if (false == is_ble_bridge_bridge_tx_ack_send_requested)
    {
      ble_bridge_bridge_tx_tx_ack_size = size;
      ble_bridge_bridge_tx_tx_ack = src;
      is_ble_bridge_bridge_tx_ack_send_requested = true;
      services_update_pipes();
      return(true);
    }
    return(false);
  }
  else
  {
    ble_bridge_bridge_tx_tx_ack_size = size;
    ble_bridge_bridge_tx_tx_ack = src;
    is_ble_bridge_bridge_tx_ack_send_requested = true;
    services_update_pipes();
    return(true);
  }
}
static bool bleduino_manufacturer_name_string_update_set(void)
{
  return(lib_aci_set_local_data(PIPE_BLEDUINO_MANUFACTURER_NAME_STRING_SET, (void*)bleduino_manufacturer_name_string_set, bleduino_manufacturer_name_string_set_size));
}

void services_set_bleduino_manufacturer_name_string(void *src, int size)
{
  bleduino_manufacturer_name_string_set_size = size;
  bleduino_manufacturer_name_string_set = src;
  is_bleduino_manufacturer_name_string_set_requested = true;
  services_update_pipes();
}

void services_update_pipes(void)
{
  if(is_gap_device_name_set_requested)
  {
    is_gap_device_name_set_requested = !(gap_device_name_update_set());
  }
  if(is_firmata_firmata_command_send_requested)
  {
    is_firmata_firmata_command_send_requested = !(firmata_firmata_command_update_send());
  }
  if(is_firmata_firmata_command_ack_send_requested)
  {
    is_firmata_firmata_command_ack_send_requested = !(firmata_firmata_command_update_send_ack());
  }
  if(is_firmata_firmata_command_set_requested)
  {
    is_firmata_firmata_command_set_requested = !(firmata_firmata_command_update_set());
  }
  if(is_ble_bridge_device_id_send_requested)
  {
    is_ble_bridge_device_id_send_requested = !(ble_bridge_device_id_update_send());
  }
  if(is_ble_bridge_device_id_ack_send_requested)
  {
    is_ble_bridge_device_id_ack_send_requested = !(ble_bridge_device_id_update_send_ack());
  }
  if(is_ble_bridge_device_id_set_requested)
  {
    is_ble_bridge_device_id_set_requested = !(ble_bridge_device_id_update_set());
  }
  if(is_ble_bridge_bridge_tx_send_requested)
  {
    is_ble_bridge_bridge_tx_send_requested = !(ble_bridge_bridge_tx_update_send());
  }
  if(is_ble_bridge_bridge_tx_ack_send_requested)
  {
    is_ble_bridge_bridge_tx_ack_send_requested = !(ble_bridge_bridge_tx_update_send_ack());
  }
  if(is_bleduino_manufacturer_name_string_set_requested)
  {
    is_bleduino_manufacturer_name_string_set_requested = !(bleduino_manufacturer_name_string_update_set());
  }
}

